obstacle_range: 5.5
raytrace_range: 6
footprint: [[-0.3, 0.2225], [-0.3, -0.2225], [0.3, -0.2225], [0.3, 0.2225]]
# robot_radius: 0.165

#inflation_radius: 0.15

#footprint_inflation: 0.15
max_obstacle_height: 0
min_obstacle_height: 0
observation_sources: scan
scan: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}


unknown_cost_value: -1
#lethal_cost_threshold: 55
map_topic: "/map"
first_map_only: false
subscription_to_updates: false
track_unknown_space: true
use_maximum: false
trinary_costmap: true




#00inflation_radius: 0.15
#00lethal_cost_threshold: 55


inflation_radius: 0.4
lethal_cost_threshold: 60
