global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 3
   publish_frequency: 1
   rolling_window: false
   resolution: 0.01
   transform_tolerance: 1.0
   static_map: true
   map_type: costmap

   
 
   

